### PR TITLE
fee overhaul & targeted long fix

### LINKED ISSUE #43: Avoid redundant calculations for `calculate_close_short_flat_plus_curve`
https://github.com/delvtech/hyperdrive/pull/916 adds a couple of negative interest checks, which requires a few internal variables used by `calculate_close_short_flat_plus_curve`. Additionally, a new `close_short_governance_fee` also includes a potentially redundant `close_short_curve_fee`. Further work is needed to remove redundant calculations of these internal variables.

### PR DESCRIPTION
**Pull request by dpaiton**
# Description
This PR is the result of an audit of the fee functions. The following changes were made (one commit per bullet):

1. revert the rounding adjustment from #97. We realized that the bug actually lies in the solidity _test utils_. This has been fixed so I reverted the rounding behavior to match.
2. update docstrings to use a more consistent format. I introduce a convention of my own to use upper-case $\Phi_{c,ol}(...)$ for the fee function and lower-case $\phi_{c}$ for the fee multiplier constant. The subscript on the fee function is the fee type $\in c, g, f$ for curve, gov, and flat; as well as the trade type $\in ol, cl, os, cs$ for opening or closing a long or short. This replaces the inconsistent method of using e.g. `c(x)` at some times and `curve_fee` at other times, or using repeat symbols for different equations.
3. add `maybe_curve_fee` arg to gov fee calculations to fix #43 and reduce computation.
4. change the rounding behavior to match solidity (note it's matching the eqs in `internal/HyperdriveBase.sol`
5. the above changes revealed a unit issue in `calculate_targeted_long` where the gov fee (and derivative) was not converted to shares. I updated my [overleaf doc](https://www.overleaf.com/read/jkngspgyqzkf#1de6ce), the docstrings, and the code itself.

# Review Checklists

Please check each item **before approving** the pull request. While going
through the checklist, it is recommended to leave comments on items that are
referenced in the checklist to make sure that they are reviewed.

- [ ] **Testing**
    - [ ] Are there new or updated unit or integration tests?
    - [ ] Do the tests cover the happy paths?
    - [ ] Do the tests cover the unhappy paths?
    - [ ] Are there an adequate number of fuzz tests to ensure that we are
          covering the full input space?
    - [ ] If matching Solidity behavior, are there differential fuzz tests that
          ensure that Rust matches Solidity?

### CODE REVIEW

File: crates/hyperdrive-math/src/long/targeted.rs [hunk 1]
```diff
@@ -229,68 +229,79 @@ impl State {
     /// is equal to
     ///
```
Comment (dpaiton) [inline crates/hyperdrive-math/src/long/targeted.rs:230]: strictly formatting change here

File: crates/hyperdrive-math/src/long/targeted.rs [hunk 2]
```diff
@@ -229,68 +229,79 @@ impl State {
...
+    ///     {y - \Delta y} \right)^{t_{s}}
     /// $$
     ///
     /// where $t_{s}$ is the time stretch constant and $z_{e,0}$ is the initial
     /// effective share reserves, and $\zeta$ is the zeta adjustment.
     /// The zeta adjustment is constant when opening a long, i.e.
     /// $\Delta \zeta = 0$, so we drop the subscript. Equivalently, for some
-    /// amount of `delta_base`$= x$ provided to open a long, we can write:
+    /// amount of `delta_base`$= \Delta x$ provided to open a long, we can write:
     ///
```
Comment (dpaiton) [inline crates/hyperdrive-math/src/long/targeted.rs:242]: math change below fixes typo; should divide gov fee by vault share price

File: crates/hyperdrive-math/src/long/targeted.rs [hunk 3]
```diff
@@ -229,68 +229,79 @@ impl State {
...
     /// $$
     ///
-    /// where $g(x)$ is the [open_long_governance_fee](long::fees::open_long_governance_fee),
-    /// $y(x)$ is the [long_amount](long::open::calculate_open_long),
-    ///
+    /// where $\Phi_{g,ol}(\Delta x)$ is the [open_long_governance_fee](long::fees::open_long_governance_fee),
+    /// $y(\Delta x)$ is the [bond_amount](long::open::calculate_open_long),
     ///
     /// To compute the derivative, we first define some auxiliary variables:
     ///
```
Comment (dpaiton) [inline crates/hyperdrive-math/src/long/targeted.rs:255]: same fix below; should be dividing gov fee by vault share price

File: crates/hyperdrive-math/src/long/targeted.rs [hunk 4]
```diff
@@ -229,68 +229,79 @@ impl State {
...
+    ///     &= \mu \left( z_{e,0} + \frac{\Delta x}{c} - \frac{\Phi_{g,ol}(\Delta x)}{c} \right) \\
+    /// b(\Delta x) &= y_0 - y(\Delta x) \\
+    /// v(\Delta x) &= \frac{a(\Delta x)}{b(\Delta x)}
     /// $$
     ///
-    /// and thus $p(x) = v(x)^t_{s}$. Given these, we can write out intermediate derivatives:
+    /// and thus $p(\Delta x) = v(\Delta x)^{t_{s}}$.
+    /// Given these, we can write out intermediate derivatives:
     ///
     /// $$
```
Comment (dpaiton) [inline crates/hyperdrive-math/src/long/targeted.rs:266]: $a'(x)$ had an error after propagating the above fixes. Other changes are cosmetic.

File: crates/hyperdrive-math/src/long/targeted.rs [hunk 5]
```diff
@@ -348,7 +360,6 @@ mod tests {
     use super::*;
     use crate::test_utils::agent::HyperdriveMathAgent;
 
-    #[ignore]
```
Comment (dpaiton) [inline crates/hyperdrive-math/src/long/targeted.rs:351]: I ran the test locally 3 times and it passed every time.

File: crates/hyperdrive-math/src/long/targeted.rs [hunk 6]
```diff
@@ -229,67 +229,79 @@ impl State {
...
         bond_amount: FixedPoint,
     ) -> Result<FixedPoint> {
-        // g'(x)
+        // g'(x) = \phi_g \phi_c (1 - p_0)
         let gov_fee_derivative = self.governance_lp_fee()
             * self.curve_fee()
             * (fixed!(1e18) - self.calculate_spot_price());
 
-        // a(x) = mu * (z_{e,0} + x/c - g(x))
+        // a(x) = mu * (z_{e,0} + 1/c (x - g(x))
```
Comment (jrhea) [inline crates/hyperdrive-math/src/long/targeted.rs:288]: nice catch

File: crates/hyperdrive-math/src/long/targeted.rs (hunk 5 above)
Comment (jrhea) [reply crates/hyperdrive-math/src/long/targeted.rs:351]: image

**Review by jrhea — APPROVED** [review]
lgtm

File: crates/hyperdrive-math/src/long/fees.rs [hunk 7]
```diff
@@ -5,36 +5,54 @@ use fixed_point_macros::fixed;
...
     /// $$
-    pub fn open_long_curve_fees(&self, base_amount: FixedPoint) -> FixedPoint {
-        self.curve_fee()
-            * ((fixed!(1e18) / self.calculate_spot_price()) - fixed!(1e18))
-            * base_amount
+    pub fn open_long_curve_fee(&self, base_amount: FixedPoint) -> FixedPoint {
+        // NOTE: Round up to overestimate the curve fee.
+        (fixed!(1e18).div_up(self.calculate_spot_price()) - fixed!(1e18))
+            .mul_up(self.curve_fee())
+            .mul_up(base_amount)
```
Comment (ryangoree) [inline crates/hyperdrive-math/src/long/fees.rs:20]: How does this work? And the units returned is in bonds?

Looking at this: https://github.com/delvtech/hyperdrive/blob/33982bba72d861b3b90cb0b4083fec30accb649f/contracts/src/internal/HyperdriveBase.sol#L773-L776

I would think we'd have to do something like this to get the curve fee in bonds:

```
curve_fee
  .mul_up(1 - spot_price)
  .mul_up(base_amount.div_up(spot_price))
  .mul_up(normalize_time_remaining)
```

Comment (jrhea) [reply crates/hyperdrive-math/src/long/fees.rs:20]: For open long we use this: https://github.com/delvtech/hyperdrive/blob/33982bba72d861b3b90cb0b4083fec30accb649f/contracts/src/internal/HyperdriveBase.sol#L718
